# -*- coding: utf-8 -*-
"""Exploratory Sales Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJ29dU6uZapy4zsKevA_-BjUjKm0O5xD
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

train = pd.read_csv('train.csv')
stores = pd.read_csv('stores.csv')
transactions = pd.read_csv('transactions.csv')
holidays = pd.read_csv('holidays_events.csv')
oil = pd.read_csv('oil.csv')

merged_df = pd.merge(train, stores, on='store_nbr', how='left')
merged_df = pd.merge(merged_df, transactions, on=['date', 'store_nbr'], how='left')
merged_df = merged_df = pd.merge(merged_df, holidays, on='date', how='left')
merged_df = pd.merge(merged_df, oil, on='date', how='left')

merged_df['date'] = pd.to_datetime(merged_df['date'])
merged_df['transactions'] = merged_df['transactions'].fillna(0)
merged_df['dcoilwtico'] = merged_df['dcoilwtico'].bfill().ffill()
holiday_cols = ['type_y', 'locale', 'locale_name', 'description', 'transferred']
for col in holiday_cols:
    merged_df[col] = merged_df[col].fillna('No Holiday/Event')

daily_sales = merged_df.groupby('date')['sales'].sum().reset_index()

sns.set_style("darkgrid")
plt.figure(figsize=(10, 5))
plt.plot(daily_sales['date'], daily_sales['sales'], color='red', label='Daily Sales')
plt.title('Sales Trend By Time', fontsize=14)
plt.xlabel('Date', fontsize=10)
plt.ylabel('Sales', fontsize=10)
plt.legend()
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

merged_df['month'] = merged_df['date'].dt.month
monthly_sales = merged_df.groupby('month')['sales'].sum()
plt.figure(figsize=(8, 4))
monthly_sales.plot(kind='bar', color='blue')
plt.title('Sales by Month', fontsize=14)
plt.xlabel('Month', fontsize=10)
plt.ylabel('Total Sales', fontsize=10)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()